erDiagram
    USUARIOS ||--o| CLIENTES : "es"
    USUARIOS ||--o| EMPLEADOS : "es"
    CATEGORIAS ||--o{ PRODUCTOS : "contiene"
    PRODUCTOS ||--o{ DETALLES_VENTA : "incluido_en"
    VENTAS ||--o{ DETALLES_VENTA : "tiene"
    CLIENTES ||--o{ VENTAS : "compra"
    EMPLEADOS ||--o{ VENTAS : "procesa"
    PRODUCTOS ||--o{ INVENTARIO : "registrado_en"
    PROVEEDORES ||--o{ COMPRA_INGREDIENTES : "suministra"
    CLIENTES ||--o{ PEDIDOS : "realiza"
    PEDIDOS ||--o{ DETALLES_PEDIDO : "incluye"

    USUARIOS {
        int usuario_id PK
        string nombre
        string correo
        string contraseña
    }

    CLIENTES {
        int cliente_id PK
        int usuario_id FK
        string telefono
        string direccion
    }

    EMPLEADOS {
        int empleado_id PK
        int usuario_id FK
        string puesto_trabajo
        decimal salario
    }

    PEDIDOS {
        int pedido_id PK
        int cliente_id FK
        datetime fecha_pedido
        string estado
        decimal total_estimado
    }

    DETALLES_PEDIDO {
        int detalle_pedido_id PK
        int pedido_id FK
        int producto_id FK
        int cantidad
    }

    PRODUCTOS {
        int producto_id PK
        string nombre
        decimal precio
        int categoria_id FK
        string unidad_medida
    }
    VENTAS {
        int venta_id PK
        int cliente_id FK
        int empleado_id FK
        datetime fecha_venta
        decimal total
        string tipo_pago
    }

    DETALLES_VENTA {
        int detalle_id PK
        int venta_id FK
        int producto_id FK
        int cantidad
        decimal precio_unitario
    }

    INVENTARIO {
        int inventario_id PK
        int producto_id FK
        int stock
        int stock_minimo
    }

    CATEGORIAS {
        int categoria_id PK
        string nombre
    }

    PROVEEDORES {
        int proveedor_id PK
        string nombre
        string telefono_contacto
        string correo
        string direccion
    }

    COMPRA_INGREDIENTES {
        int compra_id PK
        int proveedor_id FK
        string nombre_ingrediente
        decimal costo
        int cantidad
        datetime fecha_compra
    }
